image: registry.sensetime.com/zoetrope/manylinux2014_x86_64:xrprimer_ci_torch180_mmcv150

stages:
  - lint_python
  - test_cpp
  - test_python
  - deploy

before_script:
  - source /workspace/init_env.sh
  - echo $PATH
  - gcc --version
  - c++ --version
  - cmake --version
  - conda info -e

lint_python:
  stage: lint_python
  dependencies: []
  script:
    - conda activate base
    - pip install pre-commit -i https://pypi.tuna.tsinghua.edu.cn/simple
    - pip install interrogate -i https://pypi.tuna.tsinghua.edu.cn/simple
    - pre-commit install
    - export http_proxy=http://172.16.1.135:3128/
    - export https_proxy=http://172.16.1.135:3128/
    - export HTTP_PROXY=http://172.16.1.135:3128/
    - export HTTPS_PROXY=http://172.16.1.135:3128/
    - pre-commit run --all-files --verbose
    - interrogate -vinmMI -f 40 python/xrprimer/
    - unset http_proxy
    - unset https_proxy
    - unset HTTP_PROXY
    - unset HTTPS_PROXY

test_cpp:
  stage: test_cpp
  dependencies: []
  script:
    - echo "--- config conan remote and login --- "
    - conda activate py-3.7
    - pip install -r requirements/prerequisite.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
    - pip install -r requirements/test.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
    - conan remote add xrlab http://conan.kestrel.sensetime.com/artifactory/api/conan/xrlab
    - conan user -p ${CONAN_PROFILE} -r xrlab openxrlab-conan
    - cmake -S. -Bbuild -DENABLE_TEST=ON
    - cmake --build build -j4 --target install
    - cd build
    - wget -q http://10.4.11.59:18080/resources/XRlab/xrprimer.tar.gz
    - tar -xzf xrprimer.tar.gz && rm xrprimer.tar.gz
    - ln -sfn xrprimer/test test
    - echo "Start testing cpp..."
    - ./bin/test_calibrator
    - ./bin/test_image
    - ./bin/test_version
    - PYTHONPATH=./cpp/pybind python ../cpp/tests/test_multi_camera_calibrator.py
    - PYTHONPATH=./cpp/pybind python ../cpp/tests/test_pnpsolver.py

test_python:
  stage: test_python
  dependencies: []
  script:
    - unset http_proxy
    - unset https_proxy
    - unset HTTP_PROXY
    - unset HTTPS_PROXY
    - conda activate py-3.7
    - conda install ffmpeg -y
    - echo "--- config conan remote and login --- "
    - conan remote add xrlab http://conan.kestrel.sensetime.com/artifactory/api/conan/xrlab
    - conan user -p ${CONAN_PROFILE} -r xrlab openxrlab-conan
    - pip install -r requirements/prerequisite.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
    - pip install -r requirements/test.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
    - pip install -e .
    - cd python/test
    - wget -q http://10.4.11.59:18080/resources/XRlab/xrprimer.tar.gz
    - tar -xzf xrprimer.tar.gz && rm xrprimer.tar.gz
    - mv xrprimer/test/data ./
    - rm -rf xrprimer && cd ..
    - echo "Start testing python..."
    - coverage run --source xrprimer -m pytest -s test/
    - coverage report -m

D:cpp_library:
  stage: deploy
  dependencies: []
  script:
    - echo "--- config conan remote and login --- "
    - conan remote add xrlab http://conan.kestrel.sensetime.com/artifactory/api/conan/xrlab
    - conan user -p ${CONAN_PROFILE} -r xrlab openxrlab-conan
    - cmake -S. -Bbuild -DENABLE_TEST=ON
    - cmake --build build -j4 --target install
    - echo "--- upload to minio ---"
    - PKG_NAME=${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-Linux-x86_64-${CI_COMMIT_SHORT_SHA}-centos7.9.tar.gz
    - cd install && tar -zcvf ../${PKG_NAME} * && cd ../
    - wget http://file.kestrel.sensetime.com/software/mc &&  chmod +x mc
    - ./mc alias set minio ${MINIO_URL} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}
    - ./mc cp ${PKG_NAME} minio/xrprimer
  only:
    - tags
  artifacts:
    name: ${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-Linux-x86_64-${CI_COMMIT_SHA}
    when: on_success
    expire_in: 2 hrs
    paths:
      - install/

D:python_library:
  stage: deploy
  dependencies: []
  script:
    - echo $PY_VERSION
    - conda activate py-$PY_VERSION
    - echo "--- config conan remote and login --- "
    - conan remote add xrlab http://conan.kestrel.sensetime.com/artifactory/api/conan/xrlab
    - conan user -p ${CONAN_PROFILE} -r xrlab openxrlab-conan
    - echo "--- compile python wheel and upload --- "
    - python setup.py bdist_wheel
    - ls dist/
    - twine upload --repository-url https://repo.sensetime.com/repository/xrprimer/ dist/* -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD}
  parallel:
    matrix:
      - PY_VERSION: ["3.7", "3.8", "3.9", "3.10"]
  only:
    - tags

D:build_from_github:
  stage: deploy
  dependencies: []
  script:
    - export http_proxy=http://172.16.1.135:3128/
    - export https_proxy=http://172.16.1.135:3128/
    - export HTTP_PROXY=http://172.16.1.135:3128/
    - export HTTPS_PROXY=http://172.16.1.135:3128/
    - apt update && apt install libatlas-base-dev -y
    - cmake -S. -Bbuild -DBUILD_EXTERNAL=ON
    - cmake --build build --target install -j4
  when: manual

D:build_from_github_mac:
  stage: deploy
  dependencies: []
  tags:
    - "kestrel_mac_1"
  before_script:
    - echo "skip global before script"
  script:
    - export http_proxy=http://172.16.1.135:3128/
    - export https_proxy=http://172.16.1.135:3128/
    - export HTTP_PROXY=http://172.16.1.135:3128/
    - export HTTPS_PROXY=http://172.16.1.135:3128/
    - bash build-ios.sh
  when: manual
